/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Earth(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/earth.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play all animations
    Object.values(actions).forEach((action) => {
      action.reset().play();
      action.loop = THREE.LoopRepeat; // cyclic animations
    });
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Empty">
        <group name="Sphere001" position={[0.028, 0.111, -0.053]}>
          <mesh
            name="Sphere006"
            castShadow
            receiveShadow
            geometry={nodes.Sphere006.geometry}
            material={materials.land}
          />
          <mesh
            name="Sphere006_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere006_1.geometry}
            material={materials.ice}
          />
          <mesh
            name="Sphere006_2"
            castShadow
            receiveShadow
            geometry={nodes.Sphere006_2.geometry}
            material={materials.ocean}
          />
        </group>
        <group
          name="tree_2002"
          position={[0.495, 0.769, -0.394]}
          rotation={[-0.45, 0.04, -0.499]}
        >
          <mesh
            name="tree_2002_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2002_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2002_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2002_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2003"
          position={[0.49, 0.735, -0.468]}
          rotation={[-0.472, 0.033, -0.491]}
        >
          <mesh
            name="tree_2003_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2003_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2003_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2003_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2004"
          position={[0.474, 0.831, -0.296]}
          rotation={[-0.115, -0.086, -0.542]}
        >
          <mesh
            name="tree_2004_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2004_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2004_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2004_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2005"
          position={[0.407, 0.863, -0.293]}
          rotation={[-0.117, -0.092, -0.295]}
        >
          <mesh
            name="tree_2005_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2005_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2005_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2005_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2006"
          position={[0.379, 0.855, -0.351]}
          rotation={[-0.381, 0.005, -0.388]}
        >
          <mesh
            name="tree_2006_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2006_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2006_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2006_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2007"
          position={[0.305, 0.894, -0.307]}
          rotation={[0.006, -0.148, -0.279]}
        >
          <mesh
            name="tree_2007_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2007_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2007_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2007_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2008"
          position={[0.433, 0.813, -0.373]}
          rotation={[-0.41, 0.01, -0.535]}
        >
          <mesh
            name="tree_2008_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2008_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2008_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2008_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2009"
          position={[0.357, 0.769, -0.529]}
          rotation={[-0.548, 0.092, -0.289]}
        >
          <mesh
            name="tree_2009_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2009_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2009_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2009_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2010"
          position={[0.405, 0.786, -0.448]}
          rotation={[-0.523, 0.078, -0.392]}
        >
          <mesh
            name="tree_2010_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2010_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2010_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2010_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <mesh
          name="tree01001"
          castShadow
          receiveShadow
          geometry={nodes.tree01001.geometry}
          material={materials["Mat.001"]}
          position={[1.023, -0.078, -0.303]}
          rotation={[-2.357, -0.045, -1.276]}
        />
        <mesh
          name="tree01002"
          castShadow
          receiveShadow
          geometry={nodes.tree01002.geometry}
          material={materials["Mat.001"]}
          position={[0.912, 0.009, -0.516]}
          rotation={[1.755, -0.151, -2.148]}
        />
        <mesh
          name="tree01003"
          castShadow
          receiveShadow
          geometry={nodes.tree01003.geometry}
          material={materials["Mat.001"]}
          position={[0.92, -0.21, -0.449]}
          rotation={[1.923, -0.275, -1.972]}
        />
        <mesh
          name="tree01004"
          castShadow
          receiveShadow
          geometry={nodes.tree01004.geometry}
          material={materials["Mat.001"]}
          position={[0.951, -0.092, -0.396]}
          rotation={[2.017, -0.204, -2.046]}
        />
        <mesh
          name="tree01005"
          castShadow
          receiveShadow
          geometry={nodes.tree01005.geometry}
          material={materials["Mat.001"]}
          position={[0.964, 0.051, -0.354]}
          rotation={[-0.233, 0.388, -1.459]}
        />
        <mesh
          name="tree01006"
          castShadow
          receiveShadow
          geometry={nodes.tree01006.geometry}
          material={materials["Mat.001"]}
          position={[0.944, -0.239, -0.328]}
          rotation={[1.808, -0.375, -1.89]}
        />
        <mesh
          name="tree01007"
          castShadow
          receiveShadow
          geometry={nodes.tree01007.geometry}
          material={materials["Mat.001"]}
          position={[0.855, -0.167, -0.58]}
          rotation={[-1.707, 0.202, -1.003]}
        />
        <mesh
          name="tree01008"
          castShadow
          receiveShadow
          geometry={nodes.tree01008.geometry}
          material={materials["Mat.001"]}
          position={[0.934, 0.142, -0.451]}
          rotation={[3.128, -0.498, -1.746]}
        />
        <mesh
          name="tree01009"
          castShadow
          receiveShadow
          geometry={nodes.tree01009.geometry}
          material={materials["Mat.001"]}
          position={[0.836, -0.283, -0.542]}
          rotation={[0.221, 0.609, -1.913]}
        />
        <mesh
          name="tree01010"
          castShadow
          receiveShadow
          geometry={nodes.tree01010.geometry}
          material={materials["Mat.001"]}
          position={[0.894, -0.101, -0.495]}
          rotation={[0.944, 0.385, -2.086]}
        />
        <mesh
          name="pyramid001"
          castShadow
          receiveShadow
          geometry={nodes.pyramid001.geometry}
          material={materials.None}
          position={[0.844, 0.365, -0.355]}
          rotation={[-0.551, 0.268, -0.925]}
        />
        <mesh
          name="pyramid002"
          castShadow
          receiveShadow
          geometry={nodes.pyramid002.geometry}
          material={materials.None}
          position={[0.852, 0.382, -0.247]}
          rotation={[0.028, 0.319, -1.177]}
        />
        <group
          name="group989006632001"
          position={[0.571, -0.757, 0.09]}
          rotation={[-2.748, 0.602, -0.825]}
        >
          <mesh
            name="group989006632001_1"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_1.geometry}
            material={materials.mat12}
          />
          <mesh
            name="group989006632001_2"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_2.geometry}
            material={materials.mat14}
          />
          <mesh
            name="group989006632001_3"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_3.geometry}
            material={materials.mat17}
          />
          <mesh
            name="group989006632001_4"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_4.geometry}
            material={materials.mat15}
          />
          <mesh
            name="group989006632001_5"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_5.geometry}
            material={materials.mat8}
          />
          <mesh
            name="group989006632001_6"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_6.geometry}
            material={materials.mat16}
          />
          <mesh
            name="group989006632001_7"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_7.geometry}
            material={materials.mat21}
          />
          <mesh
            name="group989006632001_8"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_8.geometry}
            material={materials.mat5}
          />
          <mesh
            name="group989006632001_9"
            castShadow
            receiveShadow
            geometry={nodes.group989006632001_9.geometry}
            material={materials.mat10}
          />
        </group>
        <group
          name="group989006632002"
          position={[-0.926, 0.055, 0.172]}
          rotation={[2.816, -0.207, 1.458]}
        >
          <mesh
            name="group989006632002_1"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_1.geometry}
            material={materials.mat12}
          />
          <mesh
            name="group989006632002_2"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_2.geometry}
            material={materials.mat14}
          />
          <mesh
            name="group989006632002_3"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_3.geometry}
            material={materials.mat17}
          />
          <mesh
            name="group989006632002_4"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_4.geometry}
            material={materials.mat15}
          />
          <mesh
            name="group989006632002_5"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_5.geometry}
            material={materials.mat8}
          />
          <mesh
            name="group989006632002_6"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_6.geometry}
            material={materials.mat16}
          />
          <mesh
            name="group989006632002_7"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_7.geometry}
            material={materials.mat21}
          />
          <mesh
            name="group989006632002_8"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_8.geometry}
            material={materials.mat5}
          />
          <mesh
            name="group989006632002_9"
            castShadow
            receiveShadow
            geometry={nodes.group989006632002_9.geometry}
            material={materials.mat10}
          />
        </group>
        <mesh
          name="1368_Sailboat001"
          castShadow
          receiveShadow
          geometry={nodes["1368_Sailboat001"].geometry}
          material={materials.Mat}
          position={[0.625, 0.655, 0.264]}
          rotation={[0.363, -0.15, -0.716]}
        />
        <group
          name="tree_2011"
          position={[-0.17, 0.792, 0.556]}
          rotation={[0.684, -0.274, 0.121]}
        >
          <mesh
            name="tree_2011_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2011_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2011_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2011_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2012"
          position={[-0.197, 0.844, 0.484]}
          rotation={[0.558, -0.293, 0.181]}
        >
          <mesh
            name="tree_2012_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2012_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2012_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2012_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2013"
          position={[-0.12, 0.861, 0.483]}
          rotation={[0.497, -0.291, -0.05]}
        >
          <mesh
            name="tree_2013_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2013_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2013_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2013_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2014"
          position={[-0.265, 0.864, 0.426]}
          rotation={[0.434, -0.298, 0.262]}
        >
          <mesh
            name="tree_2014_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2014_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2014_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2014_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2015"
          position={[-0.299, 0.813, 0.496]}
          rotation={[0.687, -0.254, 0.429]}
        >
          <mesh
            name="tree_2015_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2015_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2015_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2015_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2016"
          position={[-0.072, 0.777, 0.589]}
          rotation={[0.591, -0.272, -0.012]}
        >
          <mesh
            name="tree_2016_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2016_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2016_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2016_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2017"
          position={[-0.045, 0.836, 0.508]}
          rotation={[0.588, -0.272, -0.17]}
        >
          <mesh
            name="tree_2017_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2017_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2017_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2017_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2018"
          position={[-0.168, 0.901, 0.363]}
          rotation={[0.185, -0.262, -0.14]}
        >
          <mesh
            name="tree_2018_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2018_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2018_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2018_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <group
          name="tree_2019"
          position={[-0.04, 0.889, 0.42]}
          rotation={[0.379, -0.288, -0.132]}
        >
          <mesh
            name="tree_2019_1"
            castShadow
            receiveShadow
            geometry={nodes.tree_2019_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="tree_2019_2"
            castShadow
            receiveShadow
            geometry={nodes.tree_2019_2.geometry}
            material={materials.initialShadingGroup}
          />
        </group>
        <mesh
          name="tree01011"
          castShadow
          receiveShadow
          geometry={nodes.tree01011.geometry}
          material={materials["Mat.001"]}
          position={[0.558, -0.249, 0.877]}
          rotation={[-2.073, 0.8, -2.288]}
        />
        <mesh
          name="tree01012"
          castShadow
          receiveShadow
          geometry={nodes.tree01012.geometry}
          material={materials["Mat.001"]}
          position={[0.736, -0.183, 0.741]}
          rotation={[1.838, 0.061, -0.713]}
        />
        <mesh
          name="tree01013"
          castShadow
          receiveShadow
          geometry={nodes.tree01013.geometry}
          material={materials["Mat.001"]}
          position={[0.638, -0.316, 0.771]}
          rotation={[1.982, 0.134, -0.689]}
        />
        <mesh
          name="tree01014"
          castShadow
          receiveShadow
          geometry={nodes.tree01014.geometry}
          material={materials["Mat.001"]}
          position={[0.62, -0.097, 0.826]}
          rotation={[1.868, 0.316, -0.593]}
        />
        <mesh
          name="tree01015"
          castShadow
          receiveShadow
          geometry={nodes.tree01015.geometry}
          material={materials["Mat.001"]}
          position={[0.519, -0.084, 0.89]}
          rotation={[2.212, 0.791, -0.779]}
        />
        <mesh
          name="tree01016"
          castShadow
          receiveShadow
          geometry={nodes.tree01016.geometry}
          material={materials["Mat.001"]}
          position={[0.616, -0.2, 0.812]}
          rotation={[0.373, -1.01, -1.412]}
        />
        <mesh
          name="tree01017"
          castShadow
          receiveShadow
          geometry={nodes.tree01017.geometry}
          material={materials["Mat.001"]}
          position={[0.714, -0.299, 0.682]}
          rotation={[1.368, -0.513, -0.916]}
        />
        <group
          name="model"
          position={[0.201, 0.743, 0.79]}
          rotation={[-0.502, -1.32, -1.352]}
        >
          <mesh
            name="model_1"
            castShadow
            receiveShadow
            geometry={nodes.model_1.geometry}
            material={materials.mat11}
          />
          <mesh
            name="model_2"
            castShadow
            receiveShadow
            geometry={nodes.model_2.geometry}
            material={materials["mat12.001"]}
          />
          <mesh
            name="model_3"
            castShadow
            receiveShadow
            geometry={nodes.model_3.geometry}
            material={materials.mat19}
          />
        </group>
        <mesh
          name="Environment_PalmTree_3001"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3001.geometry}
          material={materials.Atlas}
          position={[-0.008, 0.311, 0.9]}
          rotation={[1.203, -0.372, 0.121]}
        />
        <mesh
          name="Environment_PalmTree_3002"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3002.geometry}
          material={materials.Atlas}
          position={[-0.126, 0.338, 0.884]}
          rotation={[-2.273, -1.169, 2.835]}
        />
        <mesh
          name="Environment_PalmTree_3003"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3003.geometry}
          material={materials.Atlas}
          position={[-0.155, 0.417, 0.85]}
          rotation={[-2.115, 0.057, 3.012]}
        />
        <mesh
          name="Environment_PalmTree_3004"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3004.geometry}
          material={materials.Atlas}
          position={[-0.091, 0.491, 0.868]}
          rotation={[1.013, -0.954, 0.023]}
        />
        <mesh
          name="Environment_PalmTree_3005"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3005.geometry}
          material={materials.Atlas}
          position={[-0.243, 0.454, 0.867]}
          rotation={[1.211, -0.12, 0.527]}
        />
        <mesh
          name="Environment_PalmTree_3006"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3006.geometry}
          material={materials.Atlas}
          position={[-0.219, 0.386, 0.915]}
          rotation={[1.83, -0.74, 0.63]}
        />
        <mesh
          name="tree01018"
          castShadow
          receiveShadow
          geometry={nodes.tree01018.geometry}
          material={materials["Mat.001"]}
          position={[-0.708, -0.396, -0.622]}
          rotation={[0.513, -0.447, 2.259]}
        />
        <mesh
          name="tree01019"
          castShadow
          receiveShadow
          geometry={nodes.tree01019.geometry}
          material={materials["Mat.001"]}
          position={[-0.663, -0.489, -0.584]}
          rotation={[1.072, 0.28, 2.416]}
        />
        <mesh
          name="tree01020"
          castShadow
          receiveShadow
          geometry={nodes.tree01020.geometry}
          material={materials["Mat.001"]}
          position={[-0.724, -0.477, -0.52]}
          rotation={[2.836, 0.735, 1.264]}
        />
        <mesh
          name="tree01021"
          castShadow
          receiveShadow
          geometry={nodes.tree01021.geometry}
          material={materials["Mat.001"]}
          position={[-0.704, -0.432, -0.572]}
          rotation={[3.072, 0.626, 1.114]}
        />
        <mesh
          name="igloo001"
          castShadow
          receiveShadow
          geometry={nodes.igloo001.geometry}
          material={materials["None.001"]}
          position={[-0.02, -0.985, -0.182]}
          rotation={[-2.994, 0.796, 0.012]}
        />
        <mesh
          name="volcano001"
          castShadow
          receiveShadow
          geometry={nodes.volcano001.geometry}
          material={materials["None.002"]}
          position={[-0.518, -0.048, -0.798]}
          rotation={[-2.219, 0.531, 0.816]}
        />
        <mesh
          name="Environment_PalmTree_3007"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3007.geometry}
          material={materials.Atlas}
          position={[-0.289, 0.563, 0.735]}
          rotation={[2.973, -0.968, 1.97]}
        />
        <mesh
          name="Environment_PalmTree_3008"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3008.geometry}
          material={materials.Atlas}
          position={[-0.367, 0.587, 0.721]}
          rotation={[1.061, -0.21, 0.564]}
        />
        <mesh
          name="Environment_PalmTree_3009"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3009.geometry}
          material={materials.Atlas}
          position={[-0.368, 0.55, 0.79]}
          rotation={[2.931, -0.977, 1.935]}
        />
        <mesh
          name="Environment_PalmTree_3010"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3010.geometry}
          material={materials.Atlas}
          position={[-0.247, 0.505, 0.832]}
          rotation={[1.297, -0.079, 0.369]}
        />
        <mesh
          name="Environment_PalmTree_3011"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3011.geometry}
          material={materials.Atlas}
          position={[-0.301, 0.473, 0.793]}
          rotation={[1.086, -0.147, 0.262]}
        />
        <mesh
          name="Environment_PalmTree_3012"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3012.geometry}
          material={materials.Atlas}
          position={[0.423, -0.47, 0.752]}
          rotation={[-0.173, -0.807, -2.088]}
        />
        <mesh
          name="Environment_PalmTree_3013"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3013.geometry}
          material={materials.Atlas}
          position={[0.338, -0.467, 0.823]}
          rotation={[2.091, 0.011, -0.096]}
        />
        <mesh
          name="Environment_PalmTree_3014"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3014.geometry}
          material={materials.Atlas}
          position={[0.377, -0.515, 0.803]}
          rotation={[1.88, -0.736, -0.415]}
        />
        <mesh
          name="Environment_PalmTree_3015"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3015.geometry}
          material={materials.Atlas}
          position={[0.336, -0.563, 0.784]}
          rotation={[2.17, -0.807, -0.282]}
        />
        <mesh
          name="Environment_PalmTree_3016"
          castShadow
          receiveShadow
          geometry={nodes.Environment_PalmTree_3016.geometry}
          material={materials.Atlas}
          position={[0.395, -0.578, 0.731]}
          rotation={[2.533, -0.106, -0.404]}
        />
        <group name="Empty_1" rotation={[0, 0.87, 0]} scale={1.439}>
          <mesh
            name="PUSHILIN_Plane_Circle001"
            castShadow
            receiveShadow
            geometry={nodes.PUSHILIN_Plane_Circle001.geometry}
            material={materials.plane}
            position={[0.023, 1.261, -0.655]}
            rotation={[2.205, -1.371, 2.672]}
          />
          <mesh
            name="PUSHILIN_Plane_Circle002"
            castShadow
            receiveShadow
            geometry={nodes.PUSHILIN_Plane_Circle002.geometry}
            material={materials.plane}
            position={[0.006, 1.322, -0.598]}
            rotation={[2.205, -1.371, 2.672]}
          />
        </group>
        <group name="Empty001">
          <mesh
            name="Mball001"
            castShadow
            receiveShadow
            geometry={nodes.Mball001.geometry}
            material={materials["Material.001"]}
            position={[0.046, -0.442, 1.169]}
            rotation={[-1.244, 1.132, -2.999]}
          />
          <mesh
            name="Mball003"
            castShadow
            receiveShadow
            geometry={nodes.Mball003.geometry}
            material={materials["Material.001"]}
            position={[-1.184, -0.615, -0.06]}
            rotation={[-1.361, -0.359, 1.797]}
          />
          <mesh
            name="Mball005"
            castShadow
            receiveShadow
            geometry={nodes.Mball005.geometry}
            material={materials["Material.001"]}
            position={[0.467, 0.092, -1.244]}
            rotation={[1.551, 0.094, -2.876]}
          />
          <mesh
            name="Mball008"
            castShadow
            receiveShadow
            geometry={nodes.Mball008.geometry}
            material={materials["Material.001"]}
            position={[-0.509, 1.152, 0.536]}
            rotation={[1.428, -0.892, 0.903]}
          />
          <mesh
            name="Mball010"
            castShadow
            receiveShadow
            geometry={nodes.Mball010.geometry}
            material={materials["Material.001"]}
            position={[-0.459, 1.029, -0.839]}
            rotation={[-1.142, 1.137, 0.312]}
          />
          <mesh
            name="Mball013"
            castShadow
            receiveShadow
            geometry={nodes.Mball013.geometry}
            material={materials["Material.001"]}
            position={[0.886, -0.87, 0.016]}
            rotation={[2.404, -0.588, -1.164]}
          />
        </group>
        <group
          name="Pagoda"
          position={[-0.275, 0.493, -0.848]}
          rotation={[-1.032, 0.288, 0.313]}
        >
          <mesh
            name="Pagoda_1"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda_1.geometry}
            material={materials["02___Default.002"]}
          />
          <mesh
            name="Pagoda_2"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda_2.geometry}
            material={materials["_crayfishdiffuse.002"]}
          />
          <mesh
            name="Pagoda_3"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda_3.geometry}
            material={materials["03___Default.002"]}
          />
        </group>
        <group
          name="Pagoda001"
          position={[-0.159, 0.422, -0.886]}
          rotation={[0.937, -1.421, 2.084]}
        >
          <mesh
            name="Pagoda001_1"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda001_1.geometry}
            material={materials["02___Default.002"]}
          />
          <mesh
            name="Pagoda001_2"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda001_2.geometry}
            material={materials["_crayfishdiffuse.002"]}
          />
          <mesh
            name="Pagoda001_3"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda001_3.geometry}
            material={materials["03___Default.002"]}
          />
        </group>
        <group
          name="Pagoda002"
          position={[-0.12, 0.541, -0.844]}
          rotation={[-0.813, -0.865, 0.207]}
        >
          <mesh
            name="Pagoda002_1"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda002_1.geometry}
            material={materials["02___Default.002"]}
          />
          <mesh
            name="Pagoda002_2"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda002_2.geometry}
            material={materials["_crayfishdiffuse.002"]}
          />
          <mesh
            name="Pagoda002_3"
            castShadow
            receiveShadow
            geometry={nodes.Pagoda002_3.geometry}
            material={materials["03___Default.002"]}
          />
        </group>
        <group
          name="Houses_SecondAge_1_Level1"
          position={[0.658, 0.723, -0.098]}
          rotation={[-0.172, -0.006, -0.702]}
        >
          <mesh
            name="Cube218"
            castShadow
            receiveShadow
            geometry={nodes.Cube218.geometry}
            material={materials.Main}
          />
          <mesh
            name="Cube218_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube218_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube218_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube218_2.geometry}
            material={materials.Stone}
          />
          <mesh
            name="Cube218_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube218_3.geometry}
            material={materials.Wood}
          />
          <mesh
            name="Cube218_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube218_4.geometry}
            material={materials.Wood_Light}
          />
        </group>
        <group
          name="Houses_SecondAge_1_Level1001"
          position={[0.697, 0.683, -0.021]}
          rotation={[0.796, 0.404, -0.922]}
        >
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.Main}
          />
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials.Stone}
          />
          <mesh
            name="Cube001_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_3.geometry}
            material={materials.Wood}
          />
          <mesh
            name="Cube001_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_4.geometry}
            material={materials.Wood_Light}
          />
        </group>
        <group
          name="Houses_SecondAge_1_Level1002"
          position={[0.648, 0.727, -0.043]}
          rotation={[0.216, 0.231, -0.618]}
        >
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.Main}
          />
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.Stone}
          />
          <mesh
            name="Cube002_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_3.geometry}
            material={materials.Wood}
          />
          <mesh
            name="Cube002_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_4.geometry}
            material={materials.Wood_Light}
          />
        </group>
        <group
          name="Houses_SecondAge_1_Level1003"
          position={[0.644, 0.716, -0.149]}
          rotation={[0.687, 0.58, -1.217]}
        >
          <mesh
            name="Cube003"
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials.Main}
          />
          <mesh
            name="Cube003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube003_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube003_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube003_2.geometry}
            material={materials.Stone}
          />
          <mesh
            name="Cube003_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube003_3.geometry}
            material={materials.Wood}
          />
          <mesh
            name="Cube003_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube003_4.geometry}
            material={materials.Wood_Light}
          />
        </group>
        <group
          name="Houses_SecondAge_1_Level1004"
          position={[0.599, 0.75, -0.185]}
          rotation={[-0.085, 0.014, -0.656]}
        >
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials.Main}
          />
          <mesh
            name="Cube004_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube004_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_2.geometry}
            material={materials.Stone}
          />
          <mesh
            name="Cube004_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_3.geometry}
            material={materials.Wood}
          />
          <mesh
            name="Cube004_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_4.geometry}
            material={materials.Wood_Light}
          />
        </group>
        <group
          name="Houses_SecondAge_1_Level1005"
          position={[0.604, 0.755, -0.123]}
          rotation={[0.103, 0.305, -0.743]}
        >
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.Main}
          />
          <mesh
            name="Cube005_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube005_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.Stone}
          />
          <mesh
            name="Cube005_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_3.geometry}
            material={materials.Wood}
          />
          <mesh
            name="Cube005_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_4.geometry}
            material={materials.Wood_Light}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/earth.glb");
