-- users table
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "spotify_id" varchar(255) UNIQUE NOT NULL,
  "display_name" varchar(255),
  "email" varchar(255),
  "access_token" text,
  "refresh_token" text,
  "token_expires_at" timestamp,
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- songs table
CREATE TABLE "songs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "artist" varchar(255) NOT NULL,
  "duration" int NOT NULL,
  "spotify_id" varchar(255),
  "album" varchar(255),
  "album_art" text,
  "spotify_uri" varchar(255),
  "preview_url" text,
  "created_at" timestamp DEFAULT (now())
);

--  queue items table
CREATE TABLE "queue_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "song_id" int NOT NULL,
  "added_by" varchar(255),
  "added_at" timestamp DEFAULT (now())
);

-- voting to skip, etc user actions
CREATE TABLE "vote_skip" (
  "id" serial PRIMARY KEY,
  "user_id" int NOT NULL,
  "song_id" int NOT NULL,  -- Changed from queue_item_id
  "action_type" varchar(50) NOT NULL DEFAULT 'skip',
  "created_at" timestamp DEFAULT NOW(),
  UNIQUE (user_id, song_id, action_type)
);

CREATE INDEX "idx_queue_items_added_at" ON "queue_items" ("added_at");
CREATE INDEX "idx_user_actions_queue_item" ON "user_actions" ("queue_item_id");
CREATE INDEX "idx_user_actions_user" ON "user_actions" ("user_id");

ALTER TABLE "queue_items" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("id") ON DELETE CASCADE;

ALTER TABLE "user_actions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "user_actions" ADD FOREIGN KEY ("queue_item_id") REFERENCES "queue_items" ("id") ON DELETE CASCADE;