-- users table
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "spotify_id" varchar(255) UNIQUE NOT NULL,
  "display_name" varchar(255),
  "email" varchar(255),
  "access_token" text,
  "refresh_token" text,
  "token_expires_at" timestamp,
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- songs table
CREATE TABLE "songs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "artist" varchar(255) NOT NULL,
  "duration" int NOT NULL,
  "spotify_id" varchar(255),
  "album" varchar(255),
  "album_art" text,
  "spotify_uri" varchar(255),
  "preview_url" text,
  "created_at" timestamp DEFAULT (now())
);

--  queue items table
CREATE TABLE "queue_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "song_id" int NOT NULL,
  "added_by" varchar(255),
  "added_at" timestamp DEFAULT (now())
);

-- voting to skip current playing song
CREATE TABLE "vote_skip" (
  "id" serial PRIMARY KEY,
  "user_id" int NOT NULL,
  "song_id" int NOT NULL,
  "created_at" timestamp DEFAULT NOW(),
  UNIQUE (user_id, song_id)
);

CREATE INDEX "idx_queue_items_added_at" ON "queue_items" ("added_at");
CREATE INDEX "idx_vote_skip_user" ON "vote_skip" ("user_id");
CREATE INDEX "idx_vote_skip_song" ON "vote_skip" ("song_id");

ALTER TABLE "queue_items" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("id") ON DELETE CASCADE;

ALTER TABLE "vote_skip" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "vote_skip" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("id") ON DELETE CASCADE;